services:
  db:
    image: postgres:15-alpine
    container_name: searchink-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: searchink
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data